#!/bin/zsh
set -e
source env
setopt nullglob
files=(T-*.csv)
if (( ${#files[@]} > 0 )); then
   mv T-*.csv $COPYTO
fi
$PYTHON fetch.py
files=(T-*.csv)
$PYTHON balances.py > output.txt
if [[ -e err.txt ]]; then
   echo '****************************' >> output.txt
   echo 'https://beta-bridge.simplefin.org/my-account' >> output.txt
   cat err.txt >> output.txt
   echo '' >> output.txt
fi
if (( ${#files[@]} > 0 )); then
   echo "-------------------------------" >> output.txt
   $PYTHON summarize.py T-*.csv >> output.txt
fi
if [[ -z "$MAILTO" ]]; then
  echo "Not sending email"
else
  mail -s 'Finance Update' $MAILTO < output.txt
fi



